In [176]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [178]:
hrt = pd.read_csv ('Downloads/heart_disease_dataset.csv')
hrt

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [180]:
hrt.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [182]:
hrt.tail()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0

In [184]:
hrt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [186]:
hrt.size

11016

In [188]:
hrt.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [190]:
hrt.shape

(918, 12)

In [192]:
hrt.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [194]:
hrt.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [196]:
from sklearn.preprocessing import LabelEncoder

In [198]:
le = LabelEncoder()

In [200]:
Obj = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']
for i in Obj:
    hrt[i] = le.fit_transform (hrt[i])
hrt.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1              1        140          289          0           1   
1   49    0              2        160          180          0           1   
2   37    1              1        130          283          0           2   
3   48    0              0        138          214          0           1   
4   54    1              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [202]:
x = hrt.drop(['Sex', 'ChestPainType', 'FastingBS', 'RestingECG', 'ExerciseAngina', 'Oldpeak', 'ST_Slope', 'HeartDisease'], axis =1)
x

Age  RestingBP  Cholesterol  MaxHR
0     40        140          289    172
1     49        160          180    156
2     37        130          283     98
3     48        138          214    108
4     54        150          195    122
..   ...        ...          ...    ...
913   45        110          264    132
914   68        144          193    141
915   57        130          131    115
916   57        130          236    174
917   38        138          175    173

[918 rows x 4 columns]

In [204]:
y = hrt[['Sex', 'ChestPainType', 'FastingBS', 'RestingECG', 'ExerciseAngina', 'Oldpeak', 'ST_Slope', 'HeartDisease']]
y

Sex  ChestPainType  FastingBS  RestingECG  ExerciseAngina  Oldpeak  \
0      1              1          0           1               0      0.0   
1      0              2          0           1               0      1.0   
2      1              1          0           2               0      0.0   
3      0              0          0           1               1      1.5   
4      1              2          0           1               0      0.0   
..   ...            ...        ...         ...             ...      ...   
913    1              3          0           1               0      1.2   
914    1              0          1           1               0      3.4   
915    1              0          0           1               1      1.2   
916    0              1          0           0               0      0.0   
917    1              2          0           1               0      0.0   

     ST_Slope  HeartDisease  
0           2             0  
1           1             1  
2           2             0  
3           1             1  
4           2             0  
..        ...           ...  
913         1             1  
914         1             1  
915         1             1  
916         1             1  
917         2             0  

[918 rows x 8 columns]

In [206]:
from sklearn.preprocessing import MinMaxScaler
MMS = MinMaxScaler()
x1 = MMS.fit_transform(x)
x1

array([[0.24489796, 0.7       , 0.47927032, 0.78873239],
       [0.42857143, 0.8       , 0.29850746, 0.67605634],
       [0.18367347, 0.65      , 0.46932007, 0.26760563],
       ...,
       [0.59183673, 0.65      , 0.2172471 , 0.38732394],
       [0.59183673, 0.65      , 0.39137645, 0.8028169 ],
       [0.20408163, 0.69      , 0.29021559, 0.79577465]])

In [214]:
x1.shape

(918, 4)

In [216]:
x1 = pd.DataFrame(x1, columns=['Age', 'RestingBP', 'Cholesterol', 'MaxHR'])
x1

Age  RestingBP  Cholesterol     MaxHR
0    0.244898       0.70     0.479270  0.788732
1    0.428571       0.80     0.298507  0.676056
2    0.183673       0.65     0.469320  0.267606
3    0.408163       0.69     0.354892  0.338028
4    0.530612       0.75     0.323383  0.436620
..        ...        ...          ...       ...
913  0.346939       0.55     0.437811  0.507042
914  0.816327       0.72     0.320066  0.570423
915  0.591837       0.65     0.217247  0.387324
916  0.591837       0.65     0.391376  0.802817
917  0.204082       0.69     0.290216  0.795775

[918 rows x 4 columns]

In [218]:
x1.describe()

Age   RestingBP  Cholesterol       MaxHR
count  918.000000  918.000000   918.000000  918.000000
mean     0.520630    0.661983     0.329684    0.540911
std      0.192502    0.092571     0.181400    0.179298
min      0.000000    0.000000     0.000000    0.000000
25%      0.387755    0.600000     0.287313    0.422535
50%      0.530612    0.650000     0.369818    0.549296
75%      0.653061    0.700000     0.442786    0.676056
max      1.000000    1.000000     1.000000    1.000000

In [58]:
x2 = pd.concat([x1, y], axis=1)
x2

Age  RestingBP  Cholesterol     MaxHR  Sex  ChestPainType  \
0    0.244898       0.70     0.479270  0.788732    1              1   
1    0.428571       0.80     0.298507  0.676056    0              2   
2    0.183673       0.65     0.469320  0.267606    1              1   
3    0.408163       0.69     0.354892  0.338028    0              0   
4    0.530612       0.75     0.323383  0.436620    1              2   
..        ...        ...          ...       ...  ...            ...   
913  0.346939       0.55     0.437811  0.507042    1              3   
914  0.816327       0.72     0.320066  0.570423    1              0   
915  0.591837       0.65     0.217247  0.387324    1              0   
916  0.591837       0.65     0.391376  0.802817    0              1   
917  0.204082       0.69     0.290216  0.795775    1              2   

     FastingBS  RestingECG  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0            0           1               0      0.0         2             0  
1            0           1               0      1.0         1             1  
2            0           2               0      0.0         2             0  
3            0           1               1      1.5         1             1  
4            0           1               0      0.0         2             0  
..         ...         ...             ...      ...       ...           ...  
913          0           1               0      1.2         1             1  
914          1           1               0      3.4         1             1  
915          0           1               1      1.2         1             1  
916          0           0               0      0.0         1             1  
917          0           1               0      0.0         2             0  

[918 rows x 12 columns]

In [222]:
# Logistic Regression Model:

x = x2.drop('HeartDisease', axis = 1)
y = x2 ['HeartDisease']
x_1 = pd.DataFrame(x)
y_1 = pd.DataFrame(y)
print(y_1)
print(x_1)

     HeartDisease
0               0
1               1
2               0
3               1
4               0
..            ...
913             1
914             1
915             1
916             1
917             0

[918 rows x 1 columns]
          Age  RestingBP  Cholesterol     MaxHR  Sex  ChestPainType  \
0    0.244898       0.70     0.479270  0.788732    1              1   
1    0.428571       0.80     0.298507  0.676056    0              2   
2    0.183673       0.65     0.469320  0.267606    1              1   
3    0.408163       0.69     0.354892  0.338028    0              0   
4    0.530612       0.75     0.323383  0.436620    1              2   
..        ...        ...          ...       ...  ...            ...   
913  0.346939       0.55     0.437811  0.507042    1              3   
914  0.816327       0.72     0.320066  0.570423    1              0   
915  0.591837       0.65     0.217247  0.387324    1              0   
916  0.591837       0.65     0.391376  0.802817   

In [128]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25,random_state = 42)

In [130]:
from sklearn.linear_model import LogisticRegression
Log_r = LogisticRegression(max_iter = 200)

In [134]:
Model = Log_r.fit(x_train, y_train)

In [136]:
y_pred = Model.predict(x_test)
y_pred

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0], dtype=int64)

In [138]:
y_test

668    0
30     1
377    1
535    1
807    0
      ..
259    0
490    1
302    1
7      0
892    0
Name: HeartDisease, Length: 230, dtype: int64

In [140]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score, classification_report

In [142]:
print (confusion_matrix(y_test, y_pred))

[[ 86  12]
 [ 21 111]]


In [144]:
print (precision_score(y_test,y_pred))

0.9024390243902439


In [146]:
print (recall_score(y_test, y_pred))

0.8409090909090909


In [148]:
# 'should do'
print (accuracy_score(y_test,y_pred))

0.8565217391304348


In [150]:
print(f1_score(y_test,y_pred))

0.8705882352941177


In [152]:
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84        98
           1       0.90      0.84      0.87       132

    accuracy                           0.86       230
   macro avg       0.85      0.86      0.85       230
weighted avg       0.86      0.86      0.86       230



In [224]:
x_train.head(10)

Age  RestingBP  Cholesterol     MaxHR  Sex  ChestPainType  \
155  0.571429      0.775     0.567164  0.633803    1              0   
362  0.571429      0.775     0.000000  0.274648    1              2   
869  0.632653      0.750     0.351575  0.683099    1              2   
101  0.469388      0.650     0.296849  0.281690    1              0   
199  0.591837      0.650     0.510779  0.267606    0              3   
416  0.714286      0.700     0.431177  0.366197    1              0   
359  0.510204      0.525     0.000000  0.387324    1              2   
311  0.653061      0.625     0.000000  0.352113    1              0   
580  0.469388      0.655     0.252073  0.492958    1              0   
707  0.530612      0.620     0.441128  0.345070    1              0   

     FastingBS  RestingECG  ExerciseAngina  Oldpeak  ST_Slope  
155          1           1               1      3.0         1  
362          0           2               0      0.0         1  
869          1           1               0      1.6         2  
101          0           1               0      0.0         2  
199          0           1               0      1.0         1  
416          0           2               1      3.0         1  
359          0           1               0      0.0         1  
311          1           1               0      0.1         2  
580          1           0               1      1.0         1  
707          0           0               1      2.2         1

In [226]:
y_train.head(10)

155    1
362    1
869    0
101    0
199    0
416    1
359    1
311    1
580    1
707    1
Name: HeartDisease, dtype: int64

In [228]:
# Sample predictions:
# Index [1]
Model.predict ([[0.571429, 0.775, 0.567164, 0.633803, 1, 0, 1, 1, 1, 3.0, 1]]) # Right prediction

C:\AnacondaTrial\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [232]:
# Index [6]
Model.predict ([[0.714286, 0.700, 0.431177, 0.366197, 1, 0, 0, 2, 1, 3.0, 1]]) # Right prediction

C:\AnacondaTrial\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)